2022-09-21 02:23:38,317 INFO    MainThread:1843131 [wandb_setup.py:_flush():68] Configure stats pid to 1843131
2022-09-21 02:23:38,317 INFO    MainThread:1843131 [wandb_setup.py:_flush():68] Loading settings from /cluster/raid/home/zhivar.sourati/.config/wandb/settings
2022-09-21 02:23:38,317 INFO    MainThread:1843131 [wandb_setup.py:_flush():68] Loading settings from /cluster/raid/home/zhivar.sourati/logical-fallacy-identification/AMR_parsers_and_graphs/wandb/settings
2022-09-21 02:23:38,317 INFO    MainThread:1843131 [wandb_setup.py:_flush():68] Loading settings from environment variables: {'_require_service': 'True'}
2022-09-21 02:23:38,317 INFO    MainThread:1843131 [wandb_setup.py:_flush():68] Inferring run settings from compute environment: {'program_relpath': 'AMR_parsers_and_graphs/gcn.py', 'program': '/cluster/raid/home/zhivar.sourati/logical-fallacy-identification/AMR_parsers_and_graphs/gcn.py'}
2022-09-21 02:23:38,317 INFO    MainThread:1843131 [wandb_init.py:_log_setup():476] Logging user logs to /cluster/raid/home/zhivar.sourati/logical-fallacy-identification/AMR_parsers_and_graphs/wandb/run-20220921_022338-39huoebq/logs/debug.log
2022-09-21 02:23:38,317 INFO    MainThread:1843131 [wandb_init.py:_log_setup():477] Logging internal logs to /cluster/raid/home/zhivar.sourati/logical-fallacy-identification/AMR_parsers_and_graphs/wandb/run-20220921_022338-39huoebq/logs/debug-internal.log
2022-09-21 02:23:38,317 INFO    MainThread:1843131 [wandb_init.py:init():516] calling init triggers
2022-09-21 02:23:38,317 INFO    MainThread:1843131 [wandb_init.py:init():519] wandb.init called with sweep_config: {}
config: {'learning_rate': 0.0003, 'epochs': 120, 'mid_layer_dropout': 0.3, 'layers_embeddings': [128, 64, 32], 'batch_size': 16, 'edge_attr': True}
2022-09-21 02:23:38,317 INFO    MainThread:1843131 [wandb_init.py:init():569] starting backend
2022-09-21 02:23:38,317 INFO    MainThread:1843131 [wandb_init.py:init():573] setting up manager
2022-09-21 02:23:38,322 INFO    MainThread:1843131 [backend.py:_multiprocessing_setup():102] multiprocessing start_methods=fork,spawn,forkserver, using: spawn
2022-09-21 02:23:38,328 INFO    MainThread:1843131 [wandb_init.py:init():580] backend started and connected
2022-09-21 02:23:38,332 INFO    MainThread:1843131 [wandb_init.py:init():658] updated telemetry
2022-09-21 02:23:38,341 INFO    MainThread:1843131 [wandb_init.py:init():692] communicating run to backend with 30 second timeout
2022-09-21 02:23:38,599 WARNING MainThread:1843131 [wandb_init.py:init():1097] interrupted
Traceback (most recent call last):
  File "/cluster/raid/home/zhivar.sourati/anaconda3/envs/general/lib/python3.10/site-packages/wandb/sdk/wandb_init.py", line 1076, in init
    run = wi.init()
  File "/cluster/raid/home/zhivar.sourati/anaconda3/envs/general/lib/python3.10/site-packages/wandb/sdk/wandb_init.py", line 696, in init
    result = handle.wait(
  File "/cluster/raid/home/zhivar.sourati/anaconda3/envs/general/lib/python3.10/site-packages/wandb/sdk/lib/mailbox.py", line 76, in wait
    found = self._slot._get_and_clear(timeout=1)
  File "/cluster/raid/home/zhivar.sourati/anaconda3/envs/general/lib/python3.10/site-packages/wandb/sdk/lib/mailbox.py", line 35, in _get_and_clear
    if self._event.wait(timeout=timeout):
  File "/cluster/raid/home/zhivar.sourati/anaconda3/envs/general/lib/python3.10/threading.py", line 600, in wait
    signaled = self._cond.wait(timeout)
  File "/cluster/raid/home/zhivar.sourati/anaconda3/envs/general/lib/python3.10/threading.py", line 324, in wait
    gotit = waiter.acquire(True, timeout)
KeyboardInterrupt
2022-09-21 02:23:42,621 WARNING MsgRouterThr:1843131 [router.py:message_loop():77] message_loop has been closed
