
Traceback (most recent call last):
  File "/nas/home/souratih/logical-fallacy-identification/AMR_parsers_and_graphs/conceptnet_augmentation.py", line 89, in <module>
    cached_edges[(node1_label, node2_label)] = []
  File "/nas/home/souratih/logical-fallacy-identification/AMR_parsers_and_graphs/conceptnet_augmentation.py", line 39, in get_relations_between_words
    obj = make_request(query=query)
  File "/nas/home/souratih/logical-fallacy-identification/AMR_parsers_and_graphs/conceptnet_augmentation.py", line 24, in make_request
    response = requests.get(query)
  File "/nas/home/souratih/anaconda3/envs/cbr/lib/python3.9/site-packages/requests/api.py", line 73, in get
    return request("get", url, params=params, **kwargs)
  File "/nas/home/souratih/anaconda3/envs/cbr/lib/python3.9/site-packages/requests/api.py", line 59, in request
    return session.request(method=method, url=url, **kwargs)
  File "/nas/home/souratih/anaconda3/envs/cbr/lib/python3.9/site-packages/requests/sessions.py", line 587, in request
    resp = self.send(prep, **send_kwargs)
  File "/nas/home/souratih/anaconda3/envs/cbr/lib/python3.9/site-packages/requests/sessions.py", line 723, in send
    history = [resp for resp in gen]
  File "/nas/home/souratih/anaconda3/envs/cbr/lib/python3.9/site-packages/requests/sessions.py", line 723, in <listcomp>
    history = [resp for resp in gen]
  File "/nas/home/souratih/anaconda3/envs/cbr/lib/python3.9/site-packages/requests/sessions.py", line 266, in resolve_redirects
    resp = self.send(
  File "/nas/home/souratih/anaconda3/envs/cbr/lib/python3.9/site-packages/requests/sessions.py", line 701, in send
    r = adapter.send(request, **kwargs)
  File "/nas/home/souratih/anaconda3/envs/cbr/lib/python3.9/site-packages/requests/adapters.py", line 489, in send
    resp = conn.urlopen(
  File "/nas/home/souratih/anaconda3/envs/cbr/lib/python3.9/site-packages/urllib3/connectionpool.py", line 703, in urlopen
    httplib_response = self._make_request(
  File "/nas/home/souratih/anaconda3/envs/cbr/lib/python3.9/site-packages/urllib3/connectionpool.py", line 386, in _make_request
    self._validate_conn(conn)
  File "/nas/home/souratih/anaconda3/envs/cbr/lib/python3.9/site-packages/urllib3/connectionpool.py", line 1042, in _validate_conn
    conn.connect()
  File "/nas/home/souratih/anaconda3/envs/cbr/lib/python3.9/site-packages/urllib3/connection.py", line 358, in connect
    self.sock = conn = self._new_conn()
  File "/nas/home/souratih/anaconda3/envs/cbr/lib/python3.9/site-packages/urllib3/connection.py", line 174, in _new_conn
    conn = connection.create_connection(
  File "/nas/home/souratih/anaconda3/envs/cbr/lib/python3.9/site-packages/urllib3/util/connection.py", line 85, in create_connection
    sock.connect(sa)
KeyboardInterrupt